
/*
 * Editor client script for DB table venues
 * Automatically generated by http://editor.datatables.net/generator
 */

(function($){

$(document).ready(function() {
	var editor = new $.fn.dataTable.Editor( {
		"ajaxUrl": "/php/venues.php",
		"domTable": "#venues",
		"fields": [
			{
				"label": "Name",
				"name": "name",
				"type": "text"
			},
			{
				"label": "Description",
				"name": "description",
				"type": "textarea"
			},
			{
				"label": "Directions",
				"name": "directions",
				"type": "textarea"
			},
			{
				"label": "lat",
				"name": "lat",
				"type": "hidden"
			},
			{
				"label": "lng",
				"name": "lng",
				"type": "hidden"
			}
		]
	} );

	$('#venues').dataTable( {
		"sDom": "Tfrtip",
		"sAjaxSource": "/php/venues.php",
		"aoColumns": [
			{
				"mData": "venueID"
			},
			{
				"mData": "name"
			},
			{
				"mData": "description"
			},
			{
				"mData": "directions"
			},
			{
				"mData": "lat"
			},
			{
				"mData": "lng"
			}
		],
		"oTableTools": {
			"sRowSelect": "multi",
			"aButtons": [
				{ "sExtends": "editor_create", "editor": editor },
				{ "sExtends": "editor_edit",   "editor": editor },
				{ "sExtends": "editor_remove", "editor": editor }
			]
		}
	} );
} );

}(jQuery));

