<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<?php
require "dbConnect.php";
require "LoadRicoClient.php";
require "../../plugins/php/ricoLiveGridForms.php";
?>
<link href="../demo.css" type="text/css" rel="stylesheet" />

</head>
<body>

<?php
//************************************************************************************************************
//  LiveGrid-Edit Example
//************************************************************************************************************
//  Matt Brown
//************************************************************************************************************
if (OpenGridForm("", "shippers")) {
  if ($oForm->action == "table") {
    DisplayTable();
  }
  else {
    DefineFields();
  }
} else {
  echo 'open failed';
}
CloseApp();

function DisplayTable() {
  global $oForm,$oDB;
  
  echo "<table id='explanation' border='0' cellpadding='0' cellspacing='5' style='clear:both'><tr valign='top'><td>";
  echo "Base Library: <script type='text/javascript'>document.write(Rico.Lib+' '+Rico.LibVersion);</script>";
  echo "<hr>The data on this grid can be edited using pop-up forms. ";
  echo "Just click on a grid cell and then select Edit, Delete, or Add from the pop-up menu. ";
  echo "The Add and Edit forms are automatically generated by LiveGrid. ";
  echo "Updates are disabled on the database, so you will get an error message if you try to save.";
  echo "</td><td>";
  echo "</td></tr></table>";

  echo "<p><strong>Shippers Table</strong></p>";
  $oForm->options["frozenColumns"]=1;
  $oForm->options["menuEvent"]='click';
  $oForm->options["highlightElem"]='cursorRow';
  DefineFields();
  //echo "<p><textarea id='shippers_debugmsgs' rows='5' cols='80' style='font-size:smaller;'></textarea>";
}

function DefineFields() {
  global $oForm,$oDB;

  $oForm->AddEntryFieldW("ShipperID", "ID", "B", "<auto>",50);
  $oForm->AddEntryFieldW("CompanyName", "Company Name", "B", "", 150);
  $oForm->ConfirmDeleteColumn();
  $oForm->SortAsc();
  $oForm->AddEntryFieldW("Phone", "Phone Number", "B", "", 150);

  $oForm->DisplayPage();
}
?>

</body>
</html>
