<style>
	button {
		float: right;
		text-align: center;
		display: block;
		margin-top: 0;
		padding: 5px 15px;

		cursor: pointer;
		*cursor: hand;

		font-size: 14px;
		text-shadow: 0 1px 0 white;
		border: 1px solid #999;

		-webkit-border-radius: 4px;
		   -moz-border-radius: 4px;
			-ms-border-radius: 4px;
			 -o-border-radius: 4px;
				border-radius: 4px;

		-webkit-box-shadow: 1px 1px 3px #ccc;
		   -moz-box-shadow: 1px 1px 3px #ccc;
			-ms-box-shadow: 1px 1px 3px #ccc;
			 -o-box-shadow: 1px 1px 3px #ccc;
				box-shadow: 1px 1px 3px #ccc;

		/* Generated by http://www.colorzilla.com/gradient-editor/ */
		background: #ffffff; /* Old browsers */
		background: -webkit-linear-gradient(top, #ffffff 0%,#f3f3f3 89%,#f9f9f9 100%); /* Chrome10+,Safari5.1+ */
		background:    -moz-linear-gradient(top, #ffffff 0%,#f3f3f3 89%,#f9f9f9 100%); /* FF3.6+ */
		background:     -ms-linear-gradient(top, #ffffff 0%,#f3f3f3 89%,#f9f9f9 100%); /* IE10+ */
		background:      -o-linear-gradient(top, #ffffff 0%,#f3f3f3 89%,#f9f9f9 100%); /* Opera 11.10+ */
		background:         linear-gradient(top, #ffffff 0%,#f3f3f3 89%,#f9f9f9 100%); /* W3C */
		filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffff', endColorstr='#f9f9f9',GradientType=0 ); /* IE6-9 */
	}

	button:hover {
		border: 1px solid #666;

		-webkit-box-shadow: 1px 1px 3px #999;
		   -moz-box-shadow: 1px 1px 3px #999;
			-ms-box-shadow: 1px 1px 3px #999;
			 -o-box-shadow: 1px 1px 3px #999;
				box-shadow: 1px 1px 3px #999;

		background: #f3f3f3; /* Old browsers */
		background: -webkit-linear-gradient(top, #f3f3f3 0%,#e2e2e2 89%,#f4f4f4 100%); /* Chrome10+,Safari5.1+ */
		background:    -moz-linear-gradient(top, #f3f3f3 0%,#e2e2e2 89%,#f4f4f4 100%); /* FF3.6+ */
		background:     -ms-linear-gradient(top, #f3f3f3 0%,#e2e2e2 89%,#f4f4f4 100%); /* IE10+ */
		background:      -o-linear-gradient(top, #f3f3f3 0%,#e2e2e2 89%,#f4f4f4 100%); /* Opera 11.10+ */
		background:         linear-gradient(top, #f3f3f3 0%,#e2e2e2 89%,#f4f4f4 100%); /* W3C */
		filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f3f3f3', endColorstr='#f4f4f4',GradientType=0 ); /* IE6-9 */
	}

	button:active {
		-webkit-box-shadow: inset 1px 1px 3px #999;
		   -moz-box-shadow: inset 1px 1px 3px #999;
			-ms-box-shadow: inset 1px 1px 3px #999;
			 -o-box-shadow: inset 1px 1px 3px #999;
				box-shadow: inset 1px 1px 3px #999;
	}
</style>
<div class="dependencies">
	<h1>Deletion Dependencies:</h1>
	<pre><?=$dependencies?></pre>
	<button onclick="$.fancybox.close();">Confirm</button>
</div>